//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public string MaGiaoVien { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string MaUser { get; set; }
    
        public virtual C_User C_User { get; set; }
    }
}
